### ISSUE TITLE
Open Drawer on Demo doesn't seem to work

### ISSUE THREAD

**Issue by ericop** [ArthurClemens/polythene-mithril-material-components-web#7]
On the [Demo](https://arthurclemens.github.io/polythene-mithril-material-components-web/) the OPEN DRAWER doesn't seem to toggle the **Polythene List**, as it's always showing.

**Comment by ArthurClemens** [comment]
Thanks for reporting. Apparently MDW has changed the distribution of CSS. I've updated the repo to the latest version.
